/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mywork.view;

/**
 *
 * @author jiao
 */
public class HelpInternalFrame_admin extends javax.swing.JInternalFrame {

    /**
     * Creates new form HelpInternalFrame_admin
     */
    public HelpInternalFrame_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("操作指南-管理员");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？\n苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？苟利国家生死以，岂因祸福避趋之？");
        jTextArea1.setSelectionColor(new java.awt.Color(0, 204, 102));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
