package mywork.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class MainFrm_student extends javax.swing.JFrame {

	/** Creates new form MainFrm */
	public MainFrm_student() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmiSelectCourse = new javax.swing.JMenuItem();
        jmiSelectedView = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiPasswordModify = new javax.swing.JMenuItem();
        jmiSelfInfo = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("学生选课系统主界面_学生端");

        jMenu1.setText("基本操作");

        jMenu3.setText("选课");

        jmiSelectCourse.setText("选择未选课程");
        jmiSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSelectCourseActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSelectCourse);

        jmiSelectedView.setText("查看已选课程");
        jmiSelectedView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSelectedViewActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSelectedView);

        jMenu1.add(jMenu3);

        jMenu4.setText("个人信息");

        jmiPasswordModify.setText("修改密码");
        jmiPasswordModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPasswordModifyActionPerformed(evt);
            }
        });
        jMenu4.add(jmiPasswordModify);

        jmiSelfInfo.setText("学籍信息");
        jmiSelfInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSelfInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiSelfInfo);

        jMenu1.add(jMenu4);

        jmiExit.setText("退出系统");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("帮助");

        jMenuItem6.setText("操作指南");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed_student(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("联系管理员");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindAdminActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpActionPerformed_student(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed_student
        HelpInternalFrame_student helpInternalFrame_student = new HelpInternalFrame_student();
	helpInternalFrame_student.setVisible(true);
	this.table.add(helpInternalFrame_student);
    }//GEN-LAST:event_HelpActionPerformed_student

    private void FindAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindAdminActionPerformed
        FindAdminInternalFrame findAdminInternalFrame = new FindAdminInternalFrame();
	findAdminInternalFrame.setVisible(true);
	this.table.add(findAdminInternalFrame);
    }//GEN-LAST:event_FindAdminActionPerformed

	private void jmiSelfInfoActionPerformed(java.awt.event.ActionEvent evt) {
		SelfInfoInterFrm selfInfoInterFrm = new SelfInfoInterFrm();
		selfInfoInterFrm.setVisible(true);
		this.table.add(selfInfoInterFrm);
	}

	private void jmiPasswordModifyActionPerformed(java.awt.event.ActionEvent evt) {
		PasswordModifyInterFrm passwordModifyInterFrm = new PasswordModifyInterFrm();
		passwordModifyInterFrm.setVisible(true);
		this.table.add(passwordModifyInterFrm);
	}

	private void jmiSelectedViewActionPerformed(java.awt.event.ActionEvent evt) {
		SelectedViewInterFrm selectedViewInterFrm = new SelectedViewInterFrm();
		selectedViewInterFrm.setVisible(true);
		this.table.add(selectedViewInterFrm);
	}

	private void jmiSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {
		SelectCourseInterFrm selectCourseInterFrm = new SelectCourseInterFrm();
		selectCourseInterFrm.setVisible(true);
		this.table.add(selectCourseInterFrm);
	}

	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(this, "确认退出吗?");
		if (result == 0) {
			this.dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm_student().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiPasswordModify;
    private javax.swing.JMenuItem jmiSelectCourse;
    private javax.swing.JMenuItem jmiSelectedView;
    private javax.swing.JMenuItem jmiSelfInfo;
    private javax.swing.JDesktopPane table;
    // End of variables declaration//GEN-END:variables

}