/*
 * PasswordModifyInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package mywork.view;

import java.sql.Connection;

import javax.swing.JOptionPane;

import mywork.dao.StudentDao;
import mywork.model.Student;
import mywork.util.DbUtil;
import mywork.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class PasswordModifyInterFrm extends javax.swing.JInternalFrame {
	DbUtil dbUtil = new DbUtil();
	StudentDao studentDao = new StudentDao();

	/** Creates new form PasswordModifyInterFrm */
	public PasswordModifyInterFrm() {
		initComponents();
		this.setLocation(200, 50);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jb_modify = new javax.swing.JButton();
		jb_reset = new javax.swing.JButton();
		oldPasswordTxt = new javax.swing.JPasswordField();
		newPasswordTxt = new javax.swing.JPasswordField();
		passwordConfirmTxt = new javax.swing.JPasswordField();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u5bc6\u7801\u4fee\u6539");

		jLabel1.setText("\u539f\u5bc6\u7801:");

		jLabel2.setText("\u65b0\u5bc6\u7801:");

		jLabel3.setText("\u518d\u8f93\u5165\u4e00\u904d\u65b0\u5bc6\u7801:");

		jb_modify
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\modify.png")); // NOI18N
		jb_modify.setText("\u4fee\u6539");
		jb_modify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_modifyActionPerformed(evt);
			}
		});

		jb_reset
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\reset.png")); // NOI18N
		jb_reset.setText("\u91cd\u7f6e");
		jb_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_resetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(88, 88, 88)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(jLabel2)
														.addComponent(jLabel1)
														.addComponent(jb_modify))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																newPasswordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																152,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																passwordConfirmTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																152,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																oldPasswordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																152,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jb_reset))
										.addContainerGap(105, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																oldPasswordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																newPasswordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																passwordConfirmTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												41, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jb_modify)
														.addComponent(jb_reset))
										.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jb_modifyActionPerformed(java.awt.event.ActionEvent evt) {
		String oldPassword = new String(this.oldPasswordTxt.getPassword());
		String newPassword = new String(this.newPasswordTxt.getPassword());
		String passwordConfirm = new String(this.passwordConfirmTxt
				.getPassword());
		if (StringUtil.isEmpty(oldPassword)) {
			JOptionPane.showMessageDialog(this, "旧密码空!");
			return;
		}
		if (StringUtil.isEmpty(newPassword)) {
			JOptionPane.showMessageDialog(this, "新密码空!");
			return;
		}
		if (StringUtil.isEmpty(passwordConfirm)) {
			JOptionPane.showMessageDialog(this, "密码确认空!");
			return;
		}
		String rightOldPassword = LogOnFrm.currentStudent.getSpassword();
		if (!oldPassword.equals(rightOldPassword)) {
			JOptionPane.showMessageDialog(this, "修改成功!");
			return;
		}
		if (!newPassword.equals(passwordConfirm)) {
			JOptionPane.showMessageDialog(this, "修改成功!");
			return;
		}
		Connection con = null;
		int currentSno = LogOnFrm.currentStudent.getSno();
		Student student = new Student(currentSno, newPassword);

		try {
			con = dbUtil.getCon();
			int modifyNum = studentDao.PasswordModify(con, student);
			if (modifyNum == 1) {
				JOptionPane.showMessageDialog(this, "修改成功!");
				this.resetValue();

			} else {
				JOptionPane.showMessageDialog(this, "修改成功!");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, "修改成功!");
		} finally {
			try {
				dbUtil.closeCon(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void resetValue() {
		this.oldPasswordTxt.setText("");
		this.newPasswordTxt.setText("");
		this.passwordConfirmTxt.setText("");
	}

	private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {
		this.oldPasswordTxt.setText("");
		this.newPasswordTxt.setText("");
		this.passwordConfirmTxt.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton jb_modify;
	private javax.swing.JButton jb_reset;
	private javax.swing.JPasswordField newPasswordTxt;
	private javax.swing.JPasswordField oldPasswordTxt;
	private javax.swing.JPasswordField passwordConfirmTxt;
	// End of variables declaration//GEN-END:variables

}